// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsHTBP-ENo_DuZSva_iT0_Y0_Epat4VSs',
    appId: '1:1070391860136:web:b9e13867a99c3efd5f5b9d',
    messagingSenderId: '1070391860136',
    projectId: 'iitj-eats',
    authDomain: 'iitj-eats.firebaseapp.com',
    databaseURL: 'https://iitj-eats-default-rtdb.firebaseio.com',
    storageBucket: 'iitj-eats.appspot.com',
    measurementId: 'G-G4YGWFKQ2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnspiYs882IDCCGIYuqolcQUaRA5JIGX8',
    appId: '1:1070391860136:android:247024b2b0fbefe35f5b9d',
    messagingSenderId: '1070391860136',
    projectId: 'iitj-eats',
    databaseURL: 'https://iitj-eats-default-rtdb.firebaseio.com',
    storageBucket: 'iitj-eats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvG1fAdt9VLMmC1zOEjYgRxwpfNbaGE9w',
    appId: '1:1070391860136:ios:34932971ed2202905f5b9d',
    messagingSenderId: '1070391860136',
    projectId: 'iitj-eats',
    databaseURL: 'https://iitj-eats-default-rtdb.firebaseio.com',
    storageBucket: 'iitj-eats.appspot.com',
    iosClientId: '1070391860136-6u15o9h5k8uom9be9u08tjrdf7mpb0gh.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvG1fAdt9VLMmC1zOEjYgRxwpfNbaGE9w',
    appId: '1:1070391860136:ios:34932971ed2202905f5b9d',
    messagingSenderId: '1070391860136',
    projectId: 'iitj-eats',
    databaseURL: 'https://iitj-eats-default-rtdb.firebaseio.com',
    storageBucket: 'iitj-eats.appspot.com',
    iosClientId: '1070391860136-6u15o9h5k8uom9be9u08tjrdf7mpb0gh.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
